In [20]:
x=[1,2,3]
x[0]=0
x

[0, 2, 3]

In [17]:
list_one=["Tasneem","Sherif","Tawfik"]
z=list_one.pop()
z

'Tawfik'

In [1]:
x=input("enter ur mail")
x

'25'

In [1]:
x = input("Enter your email: ")  

if "@" not in x or "." not in x:  
    print("Invalid Email")  

domain = x[x.index("@") + 1 : x.index(".")]  
username = x[:x.index("@")]  


last_part = x[x.index("."):]  

if last_part == ".com":  
    domain_type = "Commercial Domain"  
elif last_part == ".edu":  
    domain_type = "Educational Domain"  
else:  
    domain_type = "Other Domain"  

 
print("Username:", username)  
print("Domain:", domain)  
print("Domain Type:", domain_type)  


Username: tasneemshreif02
Domain: gmail
Domain Type: Commercial Domain


In [ ]:
name ="Tasneem"
age= 23
s="my name is {} and my age is {}".format(name,age)
s


'my name is Tasneem and my age is 23'

In [11]:
for x in "Tasneem":
    print("Devops")
else:
        print("Python")


Devops
Devops
Devops
Devops
Devops
Devops
Devops
Python


In [4]:
for i in range(25):
    if i == 23:
        pass
    else:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
24


In [24]:

for x in range(22, 250):
    if x < 250:
        print(x)

22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249


In [6]:
x= 22
while x < 250:
    print(x)
    x += 1

22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249


In [33]:

def calculator(num1, num2, operation):
    if operation == '+':
        return num1 + num2
    elif operation == '-':
        return(num1 - num2)
    elif operation == '*':
         return(num1 * num2)
    elif operation == '/':
        return(num1 / num2)
    else:
        return("Invalid operation")
num1=float(input("Enter first number: "))
num2=float(input("Enter second number: "))
operation=input("Enter operation: ")
calculator(num1, num2, operation)

1.0

In [36]:
def function(name, age):
    print(f"my name is {name} and my age is {age}")
function( age=23,name="Tasneem" )

my name is Tasneem and my age is 23


In [7]:
z= lambda x: x+10
print(z(5))
print(type(z))

15
<class 'function'>


In [13]:
def myfunc(n):
    return lambda a : a * n
a = myfunc(2)
print(a(11))

22


In [22]:
list= [1,2,3,4,5,6,7,8]
for x in list:
    if not  x % 2 == 0:
        print(x)

1
3
5
7


In [27]:
def odd_even(x,y):
    if x % 2 == 0:
        print("even{}".format(x))
    if not y % 2 == 0:
        print("odd{}".format(y))
odd_even(2,3)

even2
odd3


In [46]:
list= [1,2,3,55,55]

def sum(list):
    list1 = 1
    for x in list:
       list1 *= x
    return list1

sum(list)


18150

In [50]:
def fun(X):
    if X <= 1:
        return X
    return X + fun(X - 1)

fun(5)

15

In [ ]:
class TASNEEM :
    name = "Tasneem"
    age = 23
    def info(tasneem): # tasneem is the object of the class can replase with self
        print(f"my name is {TASNEEM.name} and my age is {TASNEEM.age}")

s1= TASNEEM()
print(s1.info())



my name is Tasneem and my age is 23
None


In [9]:
class TASNEEM:
    def __init__(self,name):
        self.name = name
        print(f"hello {self.name}")

s1= TASNEEM("Tasneem")
s2= TASNEEM(name = str(input("Enter your name: ")))


hello Tasneem
hello tasneem


In [24]:
from abc import ABC, abstractmethod
class TASNEEM(ABC):
    @abstractmethod
    def info(self, name):
        pass

class SHERIF(TASNEEM):
    def info(self,name):
        self.name = name
        print(f"hello {self.name}")
       

s1= SHERIF()
s1.info(name= str(input("Enter your name: ")))



hello tasneem


In [25]:
class TASNEEM:
    def info(self):
        pass
class SHERIF(TASNEEM):
    def age(self):
        print("my age is 23")
    def info(self):
        print("hello")
s1= SHERIF()
s1.age()
s1.info()

my age is 23
hello


In [29]:
def fun(x):
    if x== 0:
        return 0
    if x == 1:
        return 1
    return x * fun(x-1)
fun(5)

120

In [42]:
class TASNEEM:
    def __init__(self,num):
        self.num = num
    def isprime(self):
        for x in range(2,self.num):
            if self.num % x == 0:
                return False
        return True
s1= TASNEEM(int(input("Enter number: ")))
s1.isprime()


True

In [50]:
class TASNEEM:
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2

    def dividors(self):
        mn = min(self.num1, self.num2)
        common_dividors = []
        for x in range(1, mn + 1):
            if self.num1 % x == 0 and self.num2 % x == 0:
                common_dividors.append(x)
        return common_dividors

s1 = TASNEEM(int(input("Enter first number: ")), int(input("Enter second number: ")))
s1.dividors()

[1, 2, 4, 5, 10, 20]

In [ ]:
if __name__ == "__main__":
    print("Hello World")

In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x* 5)
print(x.dot(y))

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[ 5 10 15 20 25]
130


In [4]:
M1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])   
M2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])    
print(M1)
print("=======================================")
print(M2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
